### ISSUE TITLE
Create Plan for Core-App and API Structure

### ISSUE THREAD

**Issue by Jacob-Hunt** [cse-uprc/OLGA#2]
Basically, look at what we've brainstormed and figure out which features should be part of the app's core structure and API and which features should be built on top of the API as modules (or even implemented as "apps" for the assistant).

For example, voice-recognition and voice-to-text/text-to-voice should be part of the core app and there should be API-methods for invoking these features. The ability to play word games with the user could be an app built on top of the OLGA API.

**Comment by joey-kilgore** [comment]
Initial structure and ideas from online meeting (8/30/2019) were posted [here](https://github.com/cse-uprc/OLGA/wiki/Initial-Roadmap-and-Structure)
